[tool.poetry]
name = "torrent-client"
version = "0.1.0"
description = ""
authors = ["Walter Marinho <waltersmarinho@edu.unifil.br>"]

[tool.poetry.dependencies]
python = "^3.10"
bitstring = "^3.1.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
